---
- hosts: all
  gather_facts: no
  vars_files:
    - vars.yml
    - vault.yml
  tasks:
    - name: Print something
      debug: msg="hello {{ thing }}"

    - name: Run an executable
      script: ./encryptedbinary
      register: result

    - name: Verify executable output
      debug: msg="{{ result.stdout }}"